inline_timesheet_edit_controllers:
  resource: '@InlineTimesheetEditBundle/Controller/'
  type: attribute
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'
